name: Generate Snake
on:

  schedule:

      # every 6 hours

    - cron: "0 */6 * * *"



  
  
  This command allows us to run the Action automatically from the Actions tab.


workflow_dispatch:



  
  
  The sequence of runs in this workflow:


jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-latest



# Steps represent a sequence of tasks that will be executed as part of the job
steps:

# Checks repo under $GITHUB_WORKSHOP, so your job can access it
  - uses: actions/checkout@v2

# Generates the snake  
  - uses: Platane/snk@master
    id: snake-gif
    with:
      github_user_name: visxnu
      # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
      gif_out_path: dist/github-contribution-grid-snake.gif
      svg_out_path: dist/github-contribution-grid-snake.svg

 # show the status of the build. Makes it easier for debugging (if there's any issues).
  - run: git status

  # Push the changes
  - name: Push changes
    uses: ad-m/github-push-action@master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: master
      force: true

  - uses: crazy-max/ghaction-github-pages@v2.1.3
    with:
      # the output branch we mentioned above
      target_branch: output
      build_dir: dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






Step 3. Running GitHub Actions
Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

Running Actions

Once your workflow has finished running, you should have received a green ✅ "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" ✅ then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

CodeOutput

Step 4. Adding a contribution-eating snake to your profile
Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

SnakeEating

Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?

GitHub Like a Boss (23 Part Series)
1
GitHub Desktop for better repo organisation
2
GitHub README for easy to understand code
...
19 more parts...
22
How to automatically close your issues once you merge a PR
23
How to get more suggestions from GitHub Copilot
profile
Heroku
Promoted

Heroku

This site is built on Heroku
Join the ranks of developers at Salesforce, Airbase, DEV, and more who deploy their mission critical applications on Heroku. Sign up today and launch your first app!

Get Started

Top comments (46)
Subscribe
pic
Add to the discussion
 
 
platane profile image
Platane
•
Aug 21 • Edited

Hi, First of all thanks for the precise tutorial!

There were a few changes in the action (mostly to adapt to github api), I had to change some parameters and bump the version.

Unfortunately a lot of people use the edge version ( with the tag #master ). It's a bit of a mess but the result is that this version is deprecated and can no longer work without adding some modification from the user (adding a github token as param)

The recommended usage is now this declaration:

- uses: Platane/snk/svg-only@v3
  with:
    github_user_name: ${{ github.repository_owner }}
    outputs: |
      dist/github-snake.svg
Check the readme for details about the new options


4
Like
 
 
arorasir profile image
Mohit Arora
•
Sep 24

Finally something worked :D


2
Like
 
 
mishmanners profile image
Michelle Duke
•
Sep 25

Thanks for putting this together ❤️


1
Like
 
 
kushaltanna24 profile image
KushalTanna24
•
Jun 3 '22

Work fine.! Here is mine - KushalTanna24


2
Like
 
 
1seamy profile image
seamy
•
Apr 8 • Edited

Thanks Michelle Mannering for your (dev.to/mishmanners/how-to-enable-g...) topic.

If other users wish to utilize this, kindly modify this topic;

1-Use this (thanks Platane github.com/Platane) file;

github.com/1SeaMy/1SeaMy/blob/main...

2-Use this;

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake-dark.svg)

or this

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.svg)


4
Like
 
 
msoftware profile image
Michael jentsch
•
Jul 9 '21

Great tutorial! Works for me.
Here's mine - github.com/msoftware


2
Like
 
 
gustavohgmartins profile image
Gustavo Martins
•
Sep 3 '21

Awsome! How did you change the background-color?


Like
 
 
mishmanners profile image
Michelle Duke
•
Sep 3 '21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.


1
Like
Thread
 
gustavohgmartins profile image
Gustavo Martins
•
Sep 3 '21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilá


2
Like
Thread
 
mishmanners profile image
Michelle Duke
•
Sep 3 '21

Awesome! Glad to be of help 😄


1
Like
 
 
l3on06 profile image
L3on06
•
Feb 16 '23

Hello everyone, before proceeding, please navigate to 'Settings -> Actions -> General -> Workflow Permissions' in your README.md file and select 'Read and Write' permissions. This is important because if you have other permissions selected, it may result in errors.


2
Like
 
 
unknow0074 profile image
Unknown
•
May 27

I specially created account to say thank you I almost wasted my 3 hours in wandering around to fix issue and you saved my life.** Thank you**


Like
 
 
baayah profile image
BAayah
•
Jan 11

Thank you so much! I tried to change in settings 'Contribution' to 'include my private contributions' but anyway my Readme profile doesn't show My Contributions. Could you please help me with this?
github.com/BAayah/BAayah


Like
 
 
jakon62508112 profile image
Jakob
•
Jan 20 '23 • Edited

Getting this error when I try to run workflow and after it fails:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.


1
Like
 
 
shuvajitgeek profile image
Shuvajit
•
Feb 1 '23

go to setting -> action -> and check the workflow as read and write
(run build again) hopefully you will not get error


Like
 
 
ariafatah profile image
Ariafatah
•
Sep 18 '23

github.com/ariafatah0711/ariafatah...

Check my github and change this file because I tried the file above only as much as it appears if you want to use the full one I use. And don't forget to give stars😁


1
Like
 
 
ariafatah profile image
Ariafatah
•
Sep 18 '23

If the action fails, you can go to repo settings, click action, then select general, and look at the bottom where it says read and write.


1
Like
 
 
bpolaswar profile image
Bhumesh Polaswar
•
Oct 17 '21

Great worked for me. See github.com/bpolaswar
Thanks.


2
Like
 
 
hoangtien_2k3 profile image
Hoàng Anh Tiến
•
Jan 29 '23 • Edited

It does not work for me. Can someone help me?
github.com/hoangtien2k3qx1

Error:
actions/checkout@v2, platane/snk@master, ad-m/github-push-action@master, and crazy-max/ghaction-github-pages@v2.1.3 are not allowed to be used in hoangtien2k3qx1/hoangtien2k3qx1. Actions in this workflow must be: within a repository owned by hoangtien2k3qx1.


1
Like
View full discussion (46 comments)
Code of Conduct • Report abuse
profile
Stellar Development Foundation
Promoted

Create a Rust Smart Contract

A brief tutorial on creating on setting up your local environment for Rust development
Follow our step-by-step guide to develop smart contracts on Soroban.

Start Building

Read next
msnmongare profile image
How to Run a Cron Job Every 5 Minutes in Laravel 11
Sospeter Mong'are - Oct 11

kvetoslavnovak profile image
Experiences and Caveats of Svelte 5 Migration
kvetoslavnovak - Nov 3

ayush7614 profile image
How to run for inference Llama-3_1-Nemotron-51B-Instruct?
Ayush kumar - Nov 3

clericcoder profile image
Mastering Trace Analysis with Span Links using openTelemetry and Signoz (A Practical Guide,Part 2)
Abdulsalaam Noibi - Oct 24


Michelle Duke
Follow
Developer Advocate | Hackathon Queen | International Speaker
Location
Australia
Education
The University of Melbourne
Work
Developer Advocate at GitHub
Joined
May 29, 2020
More from Michelle Duke
Release Radar · October 2024: Major updates from the open source community
#github #community #opensource #news
Release Radar · September 2024: Major updates from the open source community
#github #community #opensource #hacktoberfest
Release Radar · August 2024: Major updates from the open source community
#github #community #news #developer
profile
Heroku
Promoted

Heroku

This site is built on Heroku
Join the ranks of developers at Salesforce, Airbase, DEV, and more who deploy their mission critical applications on Heroku. Sign up today and launch your first app!

Get Started



  
  
  GitHub Action for generating a contribution graph with a snake eating your contributions.


name: Generate Snake



  
  
  Controls when the action will run. This action runs every 6 hours.


on:

  schedule:

      # every 6 hours

    - cron: "0 */6 * * *"



  
  
  This command allows us to run the Action automatically from the Actions tab.


workflow_dispatch:



  
  
  The sequence of runs in this workflow:


jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-latest



# Steps represent a sequence of tasks that will be executed as part of the job
steps:

# Checks repo under $GITHUB_WORKSHOP, so your job can access it
  - uses: actions/checkout@v2

# Generates the snake  
  - uses: Platane/snk@master
    id: snake-gif
    with:
      github_user_name: mishmanners
      # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
      gif_out_path: dist/github-contribution-grid-snake.gif
      svg_out_path: dist/github-contribution-grid-snake.svg

 # show the status of the build. Makes it easier for debugging (if there's any issues).
  - run: git status

  # Push the changes
  - name: Push changes
    uses: ad-m/github-push-action@master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: master
      force: true

  - uses: crazy-max/ghaction-github-pages@v2.1.3
    with:
      # the output branch we mentioned above
      target_branch: output
      build_dir: dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



Thank you to our Diamond Sponsor Neon for supporting our community.

DEV Community — A constructive and inclusive social network for software developers. With you every step of your journey.

Home
DEV++
Podcasts
Videos
Tags
DEV Help
Forem Shop
Advertise on DEV
DEV Challenges
DEV Showcase
About
Contact
Free Postgres Database
Guides
Software comparisons
Code of Conduct
Privacy Policy
Terms of use
Built on Forem — the open source software that powers DEV and other inclusive communities.

Made with love and Ruby on Rails. DEV Community © 2016 - 2024.
